# Generated by Django 5.0.4 on 2024-05-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorperformancemodel',
            name='on_time_delivered_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorperformancemodel',
            name='total_completed_orders',
            field=models.IntegerField(default=0),
        ),
    ]
