# Generated by Django 5.0.4 on 2024-05-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_performance', '0002_vendorperformancemodel_on_time_delivered_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorperformancemodel',
            name='average_response_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vendorperformancemodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendorperformancemodel',
            name='fulfillment_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vendorperformancemodel',
            name='on_time_delivery_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vendorperformancemodel',
            name='quality_rating_avg',
            field=models.FloatField(null=True),
        ),
    ]
