# Generated by Django 5.0.4 on 2024-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_performance', '0003_alter_vendorperformancemodel_average_response_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorperformancemodel',
            name='total_quality_rating',
            field=models.IntegerField(default=0),
        ),
    ]
