# Generated by Django 5.0.4 on 2024-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_performance', '0004_vendorperformancemodel_total_quality_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorperformancemodel',
            name='total_acknowledgment_po_s',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendorperformancemodel',
            name='total_response_time',
            field=models.IntegerField(default=0),
        ),
    ]
