# Generated by Django 5.0.4 on 2024-05-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendors_average_response_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendors',
            name='fullfillment_rate',
        ),
        migrations.AddField(
            model_name='vendors',
            name='fulfillment_rate',
            field=models.FloatField(null=True),
        ),
    ]
