# Generated by Django 5.0.4 on 2024-05-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_alter_purchaseorders_quality_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorders',
            name='order_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
