# Generated by Django 5.0.4 on 2024-05-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0005_alter_purchaseorders_acknowledgment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorders',
            name='po_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
